### ISSUE TITLE
Add Feature to update only interface status

### ISSUE THREAD

**Issue by buzzzo** [falz/netbox-device-scripts#2]
Due to the "dynamic" nature of for example, a switch, would be useful to have the following:

1) if device exists go in update mode
2) in update mode just update the status of the interfaces (eg: description, up/down)

Thx

**Comment by falz** [comment]
The general idea of these scripts is to use the actual configuration to 'do stuff'. So, if a device's interface is enabled (not shutdown), then import it that way. Likewise, if in Netbox the interface is enabled, leave it such on the device. 

Interfaces that are admin up but down (up/down if you will) are simply considered 'up' since they're administratively up.

Cheers
